# Generated by Django 4.2.7 on 2023-11-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.CharField(blank='True', max_length=150, null='True', verbose_name='slug')),
                ('body', models.TextField(verbose_name='Содержимое')),
                ('preview', models.ImageField(blank='True', null='True', upload_to='blog/', verbose_name='Изображение')),
                ('date_create', models.DateTimeField(auto_now_add=True, null='True', verbose_name='Дата создания')),
                ('is_published', models.BooleanField(blank='True', default=True, null='True', verbose_name='Признак публикации')),
                ('count_views', models.IntegerField(blank='True', null='True', verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блог',
            },
        ),
    ]
