# Generated by Django 4.2.7 on 2023-12-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='count_views',
            field=models.IntegerField(blank='True', default=0, null='True', verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Признак публикации'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='preview',
            field=models.ImageField(default='', upload_to='blog/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
