# Generated by Django 4.2.7 on 2024-01-12 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_count_views_alter_blog_is_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('set_is_published', 'Может публиковать товары')], 'verbose_name': 'Блог', 'verbose_name_plural': 'Блог'},
        ),
    ]
